### ISSUE TITLE
Add Css for the project

### ISSUE THREAD

**Issue by mihrab34** [Fatima-Bint/PyladiesBlog#3]

**Comment by georgioupanayiotis** [comment]
@mihrab34 can you please assign this to me

**Comment by 08Uzair** [comment]
Please assign this project to me

**Comment by mihrab34** [comment]
@georgioupanayiotis can you get this done today. We're looking to submit it in time for MLH open source week

**Comment by 08Uzair** [comment]
i can PR this project in 1-2 hrs please assign this to me

**Comment by georgioupanayiotis** [comment]
@mihrab34  Created the PR [here](https://github.com/Fatima-Bint/PyladiesBlog/pull/6)

**Comment by Fatima-Bint** [comment]
> @mihrab34 Created the PR [here](https://github.com/Fatima-Bint/PyladiesBlog/pull/6)

Merged

**Comment by Fatima-Bint** [comment]
> i can PR this project in 1-2 hrs please assign this to me

Sorry @08Uzair, @mihrab34 already assigned it

**Comment by georgioupanayiotis** [comment]
@Fatima-Bint  add label  HACKTOBERFEST-ACCEPTED on the PR i have created

**Comment by Fatima-Bint** [comment]
@08Uzair  the issue has been reopen so you can contribute now.

**Comment by Fatima-Bint** [comment]
> @Fatima-Bint add label HACKTOBERFEST-ACCEPTED on the PR i have created

Okay

**Comment by mihrab34** [comment]
@georgioupanayiotis  can you make the desktop view a grid and add some spacing to the text and image on the mobile view

**Comment by georgioupanayiotis** [comment]
is it ok like this? 
![Screenshot 2023-10-21 at 15 50 12](https://github.com/Fatima-Bint/PyladiesBlog/assets/1752156/9403df4c-ea6e-4bf7-8064-41d5429b6445)

**Comment by georgioupanayiotis** [comment]
created the PR [here](https://github.com/Fatima-Bint/PyladiesBlog/pull/7)

**Comment by 08Uzair** [comment]
Please assign this to me
